const pages=[...document.querySelectorAll('.page')];const navs=[...document.querySelectorAll('.nav')];function openPage(id){pages.forEach(p=>p.classList.toggle('active',p.id===id));navs.forEach(n=>n.classList.toggle('active',n.dataset.page===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='rlc')calcRLC();if(id==='response')calcResponse();if(id==='dsp')calcDSP();if(id==='link')calcLink();if(id==='antenna')calcAntenna()}navs.forEach(n=>n.addEventListener('click',()=>openPage(n.dataset.page)));document.querySelectorAll('.topbar a').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href').slice(1);if(document.getElementById(id)?.classList.contains('page')){e.preventDefault();openPage(id)}}));
function val(id){return parseFloat(document.getElementById(id).value.replace(',','.'))}function fmt(x,n=4){return Number(x).toLocaleString('ru-RU',{maximumFractionDigits:n})}
function setupCanvas(id){const c=document.getElementById(id),d=devicePixelRatio||1,r=c.getBoundingClientRect();c.width=r.width*d;c.height=(parseInt(c.getAttribute('height'))||320)*d;const x=c.getContext('2d');x.scale(d,d);return {c,x,w:r.width,h:parseInt(c.getAttribute('height'))||320}}
function drawAxes(g,xlab,ylab,title){const {x,w,h}=g;x.fillStyle='#08172a';x.fillRect(0,0,w,h);x.strokeStyle='#29435e';x.lineWidth=1;x.beginPath();x.moveTo(55,20);x.lineTo(55,h-45);x.lineTo(w-20,h-45);x.stroke();x.fillStyle='#e8f1ff';x.font='bold 15px Segoe UI';x.fillText(title,65,24);x.fillStyle='#7fa1c9';x.font='12px Segoe UI';x.fillText(xlab,w-130,h-15);x.fillText(ylab,10,45)}
function drawLine(g,data,xmin,xmax,ymin,ymax){const {x,w,h}=g;const px=i=>55+(data[i][0]-xmin)/(xmax-xmin)*(w-75);const py=v=>h-45-(v-ymin)/(ymax-ymin)*(h-70);x.strokeStyle='#49a1ff';x.lineWidth=2;x.beginPath();data.forEach((p,i)=>{const X=px(i),Y=py(p[1]);if(i===0)x.moveTo(X,Y);else x.lineTo(X,Y)});x.stroke()}
function calcRLC(){try{const R=val('R'),L=val('L'),C=val('C'),fmin=val('fmin'),fmax=val('fmax');if([R,L,C,fmin,fmax].some(v=>!(v>0))||fmin>=fmax)throw 0;const f0=1/(2*Math.PI*Math.sqrt(L*C));let data=[],maxH=0;for(let i=0;i<900;i++){const t=i/899,f=fmin*Math.pow(fmax/fmin,t),om=2*Math.PI*f,Z=Math.hypot(R,om*L-1/(om*C)),H=R/Z;data.push([Math.log10(f),H]);maxH=Math.max(maxH,H)}document.getElementById('rlcResult').innerHTML=`<b>Резонансная частота:</b> ${fmt(f0,2)} Гц<br><b>Максимум |H|:</b> ${fmt(maxH,4)}<br><br>R = ${R} Ом<br>L = ${L} Гн<br>C = ${C} Ф`;const g=setupCanvas('rlcCanvas');drawAxes(g,'Частота, Гц','|H(f)|','АЧХ RLC-цепи');drawLine(g,data,Math.log10(fmin),Math.log10(fmax),0,1.05);const {x,w,h}=g;x.fillStyle='#7fa1c9';x.font='11px Segoe UI';for(let i=0;i<7;i++){let px=55+i*(w-75)/6;let f=Math.pow(10,Math.log10(fmin)+i*(Math.log10(fmax)-Math.log10(fmin))/6);x.fillText(f.toExponential(0),px-18,h-27)}}catch(e){document.getElementById('rlcResult').textContent='Ошибка: проверьте числовые параметры.'}}
function calcResponse(){try{const b0=val('b0'),b1=val('b1'),b2=val('b2'),a1=val('a1'),a2=val('a2');let data=[];for(let i=0;i<900;i++){const w=i/899*Math.PI,zr=Math.cos(w),zi=-Math.sin(w);function mul(a,b){return [a[0]*b[0]-a[1]*b[1],a[0]*b[1]+a[1]*b[0]]}let z=[zr,zi],z2=mul(z,z),num=[b0+b1*z[0]+b2*z2[0],b1*z[1]+b2*z2[1]],den=[1+a1*z[0]+a2*z2[0],a1*z[1]+a2*z2[1]],q=mul(num,[den[0],-den[1]]),mag=20*Math.log10(Math.max(1e-12,Math.hypot(q[0],q[1])/(den[0]*den[0]+den[1]*den[1])));data.push([w,mag])}const g=setupCanvas('responseCanvas');drawAxes(g,'Нормированная угловая частота, рад','Амплитуда, дБ','АЧХ дискретной системы');let ys=data.map(p=>p[1]),mn=Math.min(...ys),mx=Math.max(...ys);drawLine(g,data,0,Math.PI,mn,mx+1); }catch(e){}}
function randn(){let u=0,v=0;while(!u)u=Math.random();while(!v)v=Math.random();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function calcDSP(){try{const f0=val('dspFreq'),fs=val('dspFs'),n=Math.max(64,Math.min(10000,Math.round(val('dspN')))),noise=val('dspNoise');let x=[];for(let i=0;i<n;i++)x.push(Math.sin(2*Math.PI*f0*i/fs)+noise*randn());let tdata=[];for(let i=0;i<Math.min(n,800);i++)tdata.push([i/fs,x[i]]);const gt=setupCanvas('dspTime');drawAxes(gt,'Время, с','Амплитуда','Смоделированный сигнал');let ymin=Math.min(...x),ymax=Math.max(...x);drawLine(gt,tdata,0,(Math.min(n,800)-1)/fs,ymin,ymax);let mags=[];for(let k=0;k<=Math.floor(n/2);k++){let re=0,im=0;for(let i=0;i<n;i++){const a=2*Math.PI*k*i/n;re+=x[i]*Math.cos(a);im-=x[i]*Math.sin(a)}mags.push([k*fs/n,Math.hypot(re,im)/n])}const gf=setupCanvas('dspFFT');drawAxes(gf,'Частота, Гц','|X(f)|','Спектр FFT');let maxf=fs/2;drawLine(gf,mags,0,maxf,0,Math.max(...mags.map(p=>p[1]))||1)}catch(e){}}
function calcLink(){try{const c=299792458,f=val('linkFreq'),d=val('linkDist'),pt=val('linkPt'),gt=val('linkGt'),gr=val('linkGr'),lam=c/f,fspl=(4*Math.PI*d/lam)**2,pr=pt*gt*gr/fspl;document.getElementById('linkResult').innerHTML=`<b>Длина волны:</b> ${fmt(lam,6)} м<br><b>FSPL:</b> ${fmt(10*Math.log10(fspl),2)} дБ<br><b>Мощность приёма:</b> ${fmt(pr,8)} Вт<br><b>Мощность приёма:</b> ${fmt(10*Math.log10(pr*1000),2)} dBm`}catch(e){document.getElementById('linkResult').textContent='Ошибка: проверьте параметры.'}}
function calcAntenna(){try{const f=val('antFreq'),lam=299792458/f;document.getElementById('antResult').innerHTML=`<b>Длина волны λ:</b> ${fmt(lam,4)} м<br><b>Четверть волны λ/4:</b> ${fmt(lam/4,4)} м<br><b>Полуволновой диполь λ/2:</b> ${fmt(lam/2,4)} м`}catch(e){document.getElementById('antResult').textContent='Ошибка: введите частоту.'}}
calcRLC();calcResponse();calcDSP();calcLink();calcAntenna();
